### ISSUE TITLE
Error in AuthController

### ISSUE THREAD

**Issue by RemiCollin** [dvlpp/sharp#3]
Had this error while calling `artisan route:list` :

PHP Fatal error:  Cannot use Illuminate\Routing\Controller as Controller because the name is already in use in /var/www/clients/ambianceetstyles.com/vendor/dvlpp/sharp/src/Dvlpp/Sharp/Http/AuthController.php on line 8

I'm not sure if the intended behaviour is to extend Illuminate\Routing\Controller or Sharp\Http\Controller, I guess PHP compiler is having the same doubts as I have.

**Comment by dvlpp** [comment]
Fixed in 3.1.15
